src/event.rs
src/world.rs

This is a small bug fix to fix building with `no-default-features` with individual feature sets.
This fixes the compile errors in #28 allowing that to go into CI.

Fix individual feature builds. Unblocks #28

---

src/world.rs

Simple applications often won't need multiple worlds sharing the same ID space, and this saves them a little boilerplate.

Convenience API for worlds alone in the universe

---

.travis.yml
src/resource.rs
src/schedule.rs

- The change to downcast-rs was incomplete, errors were not caught in
release due to travis missing release build tests.
- Added release build tests to travis. This is needed because some things are feature-gated to release builds, we need to test this case too.
- Fixed a bug case where the scheduler would make a system dependent on
itself, causing the system to never run

Fix broken resources in release build, bug in scheduler, and change travis to test release.

---

src/borrow.rs
src/cons.rs
src/event.rs
src/filter.rs
src/query.rs
src/storage.rs
tests/query_api.rs

I am pulling this into your scheduler PR, as I am currently working off that branch for my code. 
There was a good amount of documentation and clippy warnings in this branch, so I fixed them up.

[schedule-executor branch] Fix clippy/check warnings, and merge up master

---

Cargo.toml
src/resource.rs
src/schedule.rs
src/storage.rs

See https://github.com/cbreeden/fxhash for comparison of performance for our 8/12 byte keys

Change from HashMap to FxHashMap. 

---

src/query.rs

Fix impl_view_tuple! for read_types() and write_types()

---

benches/benchmarks.rs
benches/parallel_query.rs
benches/transform.rs
examples/hello_world.rs
readme.md
src/command.rs
src/lib.rs
src/query.rs
src/schedule.rs
src/system.rs
tests/query_api.rs
tests/world_api.rs

Rename immutable/mutable methods

---

src/storage.rs

I noticed this and it looked like a bug.

Archetype merge index fix

---

src/storage.rs
src/world.rs

- Added a test to ensure it doesn't happen again

Fix for #72 by passing correct data in Tags::tag_set

---

legion_core/src/query.rs
tests/query_api.rs

- Requires adding SetIndex to View::fetch

Use SetIndex in impl View for Tagged

---

Cargo.toml
example/hello_world/Cargo.toml
example/serialization/Cargo.toml
legion_core/Cargo.toml
legion_core/src/storage.rs
legion_systems/Cargo.toml

This updates all dependencies to their latest versions. Also changes a small point where explicit iterator types were used, I changed these to impl Iterators for easier usage.

Updates all dependency crates to latest versions

---

legion_systems/src/schedule.rs

I did add another vector into Schedule, maybe not the best way, but it works.

Fixed thread local systems not getting flushed

---

readme.md

Added a guidance in Getting Started for those building for WASM.

Add WASM Cargo criterion example under Getting Started

---

legion_core/src/subworld.rs
legion_core/src/world.rs

Move has_component to EntityStore

---

readme.md

Specifically change query.iter to query.iter_mut.
closes #87

Fix the example in the readme.

---

src/internals/entity.rs

- Changed `Allocate` to maintain a single counter for allocating new
Entity values. This should be a bit faster than two counters, and it's
also nice in that it allocates Entity values in increasing order rather
than reversing them within each block. That will have a more
straightforward memory stride pattern when walking through many
entities.
- When removing entities from the LocationMap, modify the len just
once at the end rather than each time we remove something.
- Compute the index within each block using a simple `%`, which will
turn into a bit-and since `BLOCK_SIZE` is an unsigned power of two
(and will surely always be).

A few minor optimizations to `LocationMap`

---

readme.md
src/internals/insert.rs
src/internals/permissions.rs
src/internals/query/filter/mod.rs
src/internals/serialize/id.rs
src/internals/serialize/mod.rs
src/internals/subworld.rs
src/internals/world.rs
src/lib.rs
src/query.rs
src/serialize.rs
src/storage.rs
src/world.rs

- Switch to intra-doc links
- Fix broken links in readme.md

Fix broken links in docs & readme.md

---

src/internals/entity.rs

This fixes #224. I followed @tomgillen's advice on Discord and made the creation of new `Entity`s use `new_unchecked`. I added `debug_assert_ne` and comments to make sure future editors know the safety conditions.

Use NonZeroU64 to store entity IDs

---

src/internals/systems/command.rs

This is just a quick fix changing a `Fn` closure to be `FnOnce`.
I'm not aware of any cases where the exec_mut closure would be called more than once, and making this change allows non-`Copy` values to be used a lot more easily. This should fix #246.
I added an example to the tests, and have also compiled my own project using my fork and making use of this feature.

Make command buffer exec_mut closure FnOnce

---

src/internals/systems/command.rs

Reverts amethyst/legion#287
CI did not properly run, @charlie-hadden will revert, re-open a PR with fixes for 
https://github.com/amethyst/legion/actions/runs/1300410145

Revert "Make command buffer exec_mut closure FnOnce"
