amethyst/legion

- src/lib.rs
Currently Universe::new() constructs a random name
This is particularly problematic for wasm environments which need to
configure `rand` with different features (`names` depends on `rand`).
A simple workaround is to allow an optional name provided to
Universe::new(). Another benefit is that the user can
associate meaningful names with universes.
> optional universe name

- Cargo.toml
- clippy.toml
- rustfmt.toml
- src/borrows.rs
- src/experimental/borrow.rs
- src/experimental/entity.rs
- src/experimental/filter.rs
- src/experimental/lib.rs
- src/experimental/mod.rs
- src/experimental/storage.rs
- src/experimental/world.rs
- src/lib.rs
- src/query.rs
- src/storage.rs
- tests/query_api.rs
- tests/world_api.rs
This is strictly ergonomic changes. I went through the effort of getting Legion to completely pass a normal clippy pass. This included small changes like passing newtypes of primitives by value, some idiomatic changes to iterator usage (find instead of filter+next, etc) and some pointer arithmetic changes for clarity, and finally some derivative changes to be more in line with "Default is default" idiom.
This was mainly so i could begin work while actively using clippy on the repo.
> Initial rust format and clippy pass to allow for using clippy and format

- Cargo.toml
- src/resource.rs
I believe it and downcast-rs are functionally equivalent. It still builds, at least; let me know if I missed a subtlety!
> Remove redundant mopa dependency

- src/resource.rs
`Fetch` and `FetchMut` for resources do not conditionally implement `Debug` if the underlying `T` does. This fixes that, so you can transparently use `Debug` on the inner type for a `Fetch.
> Implement debug for res Fetch types where applicable

- .travis.yml
Ensures no accidental interdependencies arise.
This does in fact fail due to some existing interdependencies, and probably shouldn't be merged until they're fixed.
> Test features individually in CI

- benches/benchmarks.rs
- benches/parallel_query.rs
- benches/transform.rs
- examples/hello_world.rs
- readme.md
- src/command.rs
- src/lib.rs
- src/query.rs
- src/schedule.rs
- src/system.rs
- src/world.rs
- tests/query_api.rs
- tests/world_api.rs
Changed `World` and `Query` APIs to require `&mut World`, such that it is statically impossible to write safe code with unsound borrowing. New unsafe `_unchecked` alternatives have been added with the previous behaviour.
This required changing the `PreparedQuery` APIs to also require they be given a `PreparedWorld` reference, in order to control whether a system can execute two of its queries at the same time.
`PreparedWorld` now provides more of the API that is available on `World`. `PreparedWorld` allows random access to components and archetypes that a system's queries declare access to. `SystemBuilder::[read/write]_component` can now be used to mark the system as accessing all archetypes.
> Improved public API soundess

- .github/workflows/ci.yml
- src/query.rs
- tests/query_api.rs
- Remove extra dead comment
- Fixed `Chunk` pulling from the wrong chunk index. It was querying as chunk_index when it should have been set index
> Fix incorrect Chunk iterator on tags during iter_chunks

- src/filter.rs
- tests/query_api.rs
With the new optional components queries (`TryRead` and `TryWrite`) it will be useful to refer to this optional components while filtering by change. For now situation when optional component is missing on entity, but present in the filter results in panic. Not quite sure with the actual implementation though.
> Fix change filter on optional components

- src/borrow.rs
Simple enough. 
- Release builds were broken at the moment, as there was a missing `use` in `borrow` for `PhantomData` when debug assertions were disabled.
- derived `impl Debug where T: Debug` on `AtomicRefCell`
> Add impl T: Debug for AtomicRefCell and Fix release builds

- Cargo.toml
- src/command.rs
- src/event.rs
- src/storage.rs
- src/world.rs
When building without `par-schedule` feature one only needs the crossbeam-channel crate, not all the other parts of crossbeam. 
This reduces compile times when building with few features. We ran into this because we are building with `default-features = false` and wanted to reduce amount of dependencies and improve build times.
And when building with that feature, we only additionally need crossbeam-queue. Although in practice in that case one gets rest of crossbeam due to rayon.
> Include only needed crossbeam dependencies

- src/storage.rs
Fixes #60 
Simply moving the `let mut last = slice.len() - 1;` a few lines down should do the trick given that slice cannot have a len of zero at that point due to the branching return.
> fix subtracting overflow in World::defrag

- src/command.rs
- src/system.rs
This removes SegQueue from CommandBuffer. it was causing out-of-order command buffer operations, leading to panics due to things occuring out of order. This also refs #53, as it removes another crossbeam usage.
This also adds a few tests to world for a bug I was attempting to track.
> Remove SegQueue from CommandBuffer & Additional Tests

- docs/book/book.toml
- docs/book/src/01_introduction.md
- docs/book/src/SUMMARY.md
- examples/hello_world.rs
- examples/serde.rs
- src/borrow.rs
- src/command.rs
- src/de.rs
- src/entity.rs
- src/resource.rs
- src/schedule.rs
- src/system.rs
- src/world.rs
- tests/world_api.rs
This commit makes a few internals changes, but not much of a public API change. The aim of this PR is completing the CommandBuffer implementation to a working order. This current implementation does not consider inefficiencies in the implementation (a buffer copy, basically).
The command buffer implementation has been shifted, to taking N entities out of the world and keeping them resident to the buffer for usage. Every frame, the Scheduler now calls `resize` on the command buffer, having it take more entities if it needs. This means any given buffer can only create N entities any given frame. This is a logical limitation for the system, I believe.
This made some changes to the `World` object:
- Added a `command_buffer_size` parameter to `World`, defaulting to 64 via …
> Finish the CommandBuffer implementation

- legion_core/src/entity.rs
- tests/world_api.rs
Add a test to reproduce the issue and address it by resetting EntityAllocators to a safe default state before returning them to the pool
> Fix #92 "panic occurs when repeatedly deleting worlds with entities still allocated in them

- Cargo.toml
- legion_core/src/storage.rs
- tests/world_api.rs
Not sure if you consider it a bug that the event doesn't fire if a world is dropped. I have another PR that adds support for deleting all entities. This change would ensure events fire in that case too.
> Fire RemoveEntity events when a ComponentStorage is dropped

- legion_core/src/entity.rs
- legion_core/src/storage.rs
- legion_core/src/world.rs
- tests/world_api.rs
This change deletes all entities from the entity allocator (the code that was in Drop was moved to a new function delete_all_entities and now Drop calls that.) It also drops all the chunks in storage which in turn calls drop on all components. Event subscriptions and the command buffer are left intact.
> Add support for removing all entity data

- legion_core/src/storage.rs
- legion_core/src/world.rs
- tests/world_api.rs
This is implemented by iterating component storage to find live entities. I'm using this for comparing two worlds and detecting what has been added between the two worlds.
The function enumerate_entities already existed. I considered renaming it to enumerate_entity_locations but that seemed a bit long. Also, I see more usages of iter_* than enumerate_* in standard library, so maybe it's a tiny bit more idiomatic, maybe?
I don't have a strong opinion about the naming though. Happy to change it to whatever you prefer!
> Add support iterating across all entities

- legion_core/src/storage.rs
When I receive an event I can't access the `ArchetypeId`. All the other index types do have public fields. I propose to do the same for this type. I need to know the internals of this type in order to use the events. Otherwise, they are pretty useless, because reconstruction of the game world can't happen. 
```rust
ArchetypeCreated(ArchetypeId(WorldId(1, 0), ArchetypeIndex(0)))
ChunkCreated(ChunkId(ArchetypeId(WorldId(1, 0), ArchetypeIndex(0)), SetIndex(0), ChunkIndex(0)))
EntityInserted(Entity { index: 63, version: 1 }, ChunkId(ArchetypeId(WorldId(1, 0), ArchetypeIndex(0)), SetIndex(0), ChunkIndex(0)))
```
> Made getters ArchetypeId public.

- legion_systems/src/schedule.rs
- legion_systems/src/system.rs
- Track reads as well as writes
- Writes are dependent on reads to avoid simultanious execution
- Reads handled after writes to prevent overriting last read
> Track component changes like resource changes

- legion_core/src/borrow.rs
I needed this to deal with `TryWrite<...>` in a query so I could pass in an `Option<RefMut<...>>` to a function and interact with the interior by writing `if Some(x) = x.as_mut() { ... }`. I'm not sure that was necessarily the best way of doing it, but I figure not implementing `AsMut` for these two structs was probably an oversight so here's a pull request! :smile:
> Add AsMut for RefMut and RefMapMut

- legion_systems/src/system.rs
#129 brought up a soundness issue which looked like it should have been solved by the borrow checker already. Lifetime annotations seem to resolve it.
> Added missing lifetime annotations for SubWorld

- legion_core/src/world.rs
- tests/world_api.rs
This returns the ComponentTypeId/ComponentMeta and TagTypeId/TagMeta for all components/tags associated with an entity. We are using this for serialization/deserialization.
This was originally embedded in #113 but I'm pulling it out separately
> Entity component tag types

- legion_core/src/query.rs
- legion_systems/src/system.rs
The current documentation of these functions was unclear to me, so I improved it based on what I think is correct. If my interpretation is wrong, I'll fix it.
> Clearer documentation of safe usage of _unchecked functions on queries

- Cargo.toml
Legion uses the Uuid::new_v4 function in `src/internals/entity.rs` and it
correctly depends on the uuid create with feature 'v4' enabled. However,
for wasm targets you must additionally enable either the stdweb or
wasm-bindgen feature on that crate: https://github.com/uuid-rs/uuid#dependencies
Therefore, re-export those features so they may be enabled by downstream
libraries/binaries that target wasm and use this crate.
> Fix compilation to wasm: the Uuid::new_v4() function is not found

- Cargo.toml
- codegen/Cargo.toml
- codegen/src/lib.rs
- codegen/tests/basic.rs
- codegen/tests/failures.rs
- codegen/tests/failures/par_mut_command.rs
- codegen/tests/failures/par_mut_command.stderr
- codegen/tests/failures/par_mut_resource.rs
- codegen/tests/failures/par_mut_resource.stderr
- codegen/tests/failures/par_mut_world.rs
- codegen/tests/failures/par_mut_world.stderr
- codegen/tests/failures/value_argument.rs
- codegen/tests/failures/value_argument.stderr
- codegen/tests/for_each.rs
- codegen/tests/par_for_each.rs
- readme.md
- src/internals/query/view/mod.rs
- src/internals/systems/schedule.rs
- src/internals/systems/system.rs
- src/lib.rs
- tests/systems.rs
This PR adds a `#[system]` procedural macro to legion, behind the "codegen" feature flag (enabled by default), which generates the code dealing with manually constructing systems with the `SystemBuilder` API, as discussed in #31. The function maked with the attribute is left as-is, so auto-complete and other IDE tooling continue to function as normal.
To copy and paste the docs for the macro:
Wraps a function in a system, and generates a new function which constructs that system.
There are three types of systems: simple (default), for_each and par_for_each. By default, the system macro will create a new function named `<attributed_fn_name>_system` which can be called to construct the system.
By default, the system function is called once when the system runs.
```rust
#[system]
fn …
```
> #[system] procedural macro

- Cargo.toml
- src/internals/query/view/read.rs
- src/internals/query/view/try_read.rs
- src/internals/query/view/try_write.rs
- src/internals/query/view/write.rs
- src/internals/systems/resources.rs
- src/internals/systems/schedule.rs
- src/internals/systems/system.rs
- src/systems.rs
Resources which are !Sync can now be stored inside Resources collections. Systems which attempt to access such resources will themselves be marked as !Sync and cannot be scheduled via `add_system`, but must be scheduled as thread-local via `add_thread_local`.
This is a breaking change as `Resources` is now no longer `Send` or `Sync`, as it may own resources which themselves need to stay on the main thread.
> Allow !Sync resources to be stored in Resources

- codegen/src/lib.rs
This wording confused me.  It sort of sounds like systems only run once, which doesn't make sense.  Or maybe it meant the system is only setup once--but I don't know why that would be important information at this spot in the documentation.  I _think_ this new wording conveys what was actually intended.
> Clarify what runs when

- src/internals/query/mod.rs
- src/world.rs
Some crates put examples on the struct, some on the module, I couldn't find the examples the first time i was looking for them because i am more used to docs on the struct so now i linked them explicitly. The standard library does it like this (e.g. [Rc](https://doc.rust-lang.org/std/rc/struct.Rc.html) struct links to rc module).
I would do the same for World vs world but it seems the links wouldn't sometimes work as reported in #195.
Also unified whether just "Entity" or "Entity ID" is part of the link.
> 2 tiny docs improvements

- readme.md
It seems stdweb development is dead so it might be better to show that wasm-bindgen in the example.
> Prefer wasm-bindgen over stdweb in readme

- readme.md
I was puzzled why i was able to compile legion to WASM without the feature - it appears to be only used in serialization so there's no need for everyone to enable it unless they use serialization.
> Improve WASM feature docs

- Cargo.toml
Also remove the badges section since (a) legion now uses Github actions and (b) the badges section will actually be deprecated. See https://github.com/rust-lang/crates.io/issues/2436 for details.
> Update repository link in Cargo.toml

- src/internals/serialize/id.rs
- src/internals/serialize/mod.rs
After reading about [the recent improvements to Miri](https://www.ralfj.de/blog/2020/09/28/miri.html), I tried using it to run Legion's tests. Most of them succeed, but `internals::serialize::test::serialize_bincode` and `internals::serialize::test::serialize_json` both panic for reasons I haven't looked into, and because they run in the same thread, the second one finds a dangling pointer and triggers an error in Miri.
This pull request fixes that problem, leaving both test results as panics rather than undefined behavior. The comment suggested using `catch_unwind` for this, but I used the more common and probably more efficient pattern of a guard struct with a `Drop` implementation that cleans up. I also added a small test to make sure Miri always has the opportunity to catch this bug, …
> Use a drop guard to prevent leaving a dangling reference in internals::serialize::id::run_as_context

- src/internals/hash.rs
This avoids the need for u64::from_ne_bytes.
> Use write_u64 to special-case hashing 64 bit values

- codegen/src/lib.rs
When a user misuse `#[read_component]` macro (ex. forget specifying component type)
Rust compiler shows error message at `#[system]` line:
```
$ cargo test no_component_type
Compiling legion_codegen v0.3.0 (/Users/admin/tmp/legion/codegen)
Compiling legion v0.3.1 (/Users/admin/tmp/legion)
error: expected component type
--> tests/dummy.rs:7:5
|
7 |     #[system]
|     ^^^^^^^^^
|
= note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
...
```
Same happens also on `#[filter]` macro.
This change fixes the problem:
```
$ cargo test no_component_type
Compiling legion v0.3.1 (/Users/admin/tmp/legion)
error: expected component type
--> tests/dummy.rs:8:7
|
8 |     #[read_component]
|       ^^^^^^^^^^^^^^
...
```
Return appropriate `Span` …
> Show appropriate error position on invalid macro usage

- src/internals/systems/resources.rs
When fetching resources via `ResourceSet`, if the resource does not exist, it shows the standard "unwrap" error message. This is not very helpful when debugging, so this adds a more descriptive error message.
> Better error message when fetching nonexistent resources

- src/systems.rs
Noticed this re-export was missing since the type didn't get linked properly on the return type in https://docs.rs/legion/0.3.1/legion/struct.Resources.html#method.get_mut.
> Re-export FetchMut from systems

- src/internals/systems/command.rs
- src/internals/systems/schedule.rs
This implements #212 by adding `&mut Resources` arguments to some existing functions.
> Add Resources to CommandBuffer::exec_mut and ::flush

- src/internals/serialize/mod.rs
- src/serialize.rs
This enables `serialize::Registry` to take different `Entity`<->`SerializedID` maps than the default (`Canon`).
I'm trying to access `Entity`<->`SerializedID` maps outside of just the registry, which isn't supported by the `Canon` implementation, which is the trigger for opening this pull request. Looking at the code though, I think the intention was to make this trait public anyways.
> Adds CustomEntitySerializer to the public API

- src/internals/serialize/mod.rs
Changes `Registry` to use `Arc<RwLock<S: CustomEntitySerializer>`
This way `Canon` (and other implementations of `CustomEntitySerializer`) can be used outside of Registry, which is useful for mapping world entities to data outside of legion. RwLock is more friedly for this use case, and requiring `Send + Sync` on `S` instead of just `Send` doesn't seem too burdensome.
> Extract canon from registry

- src/query.rs
Adding `EntityFilterTuple` to the public API enables complex queries to be stored in application data structures. I'm trying to create a query that has a chain of `Or` filters tied to `maybe_changed::<component_type>()` filters. I want this query to be stored in a data structure such that I can check if I should serialize the world or not after executing my schedule. As-is, I can't because the final query type contains `EntityFilterTuple`.
> adds `EntityFilterTuple` to the public API

- src/internals/systems/schedule.rs
This is an attempt to implement #198. I've followed the guidelines for the `Debug` trait relatively strictly, so it mostly shows the exact internal state of the various types. I could make some of it a bit more clean and easy to read, for example by grouping the values of `Executor` by index, or showing only the system names instead of the full `SystemId`, but I first wanted some feedback on whether such a deviation from standard `Debug` output would be ok.
I introduced an instance of `unsafe` in the `SystemBox` implementation. I don't know if that is sound, that should be verified by someone who knows better.
Perhaps implementing this using the `Debug` trait is the wrong approach here, I just went with that because the original issue described it that way.
> Implement Debug for Schedule, Executor and other subtypes

- src/internals/permissions.rs
- src/internals/query/mod.rs
- src/internals/storage/group.rs
- src/internals/subworld.rs
- src/internals/systems/system.rs
This function is only called when splitting a systems subworld as only system subworlds use `ComponentAccess::Allow`.
I believe that if a split includes read only access to a component then both subworlds should be able to read that component.  It would be consistent with documentation.
As of now only the left subworld gets read access to read-only components in the View.
> allow read in both subworlds within split in system

- src/internals/systems/resources.rs
> Fetching a nonexistent resource prints the name of a type

- Cargo.toml
- src/internals/query/view/read.rs
- src/internals/query/view/try_read.rs
- src/internals/query/view/try_write.rs
- src/internals/query/view/write.rs
- src/internals/storage/slicevec.rs
- src/internals/systems/command.rs
All uses of [`derivative`](https://crates.io/crates/derivative) are trivial. Removing this dependency may slightly improve compile time.
Note: test failures due to `compare_and_swap`, which has been [deprecated](https://github.com/rust-lang/rust/pull/79261).
> Removing derivative from dependencies

- Cargo.toml
- src/internals/serialize/de.rs
- src/internals/serialize/id.rs
- src/internals/serialize/mod.rs
- src/internals/serialize/ser.rs
- src/internals/world.rs
- src/serialize.rs
The following changes are made, some of which are breaking.
- `Canon` is moved out of `Registry` so that it's now a free-standing type. That way there's a clear separation of concerns, between handling `Entity` and handling component types.
- The `with_entity_serializer` methods on `WorldSerializer` and `WorldDeserializer` are consequently removed, while `World::as_serializable` and `Registry::as_deserialize(_into_world)` take an extra `EntitySerializer` argument.
- `Canon` now handles its locking internally, instead of having to be wrapped in a lock.
- `CustomEntitySerializer`'s methods take `&self`, possible due to the change above.
- `EntitySerializer` now has a blanket implementation for anything that implements `CustomEntitySerializer`.
- The custom `run_as_context` logic is replaced …
> Some rearranging of serialize/deserialize code

- src/internals/query/mod.rs
Parallel iterators were iterating over all chunks rather than their split sub-set... This is obviously a massively critical bug.
Fixes #239
> Fix parallel chunk iterator using entire index instead of split slice

- codegen/src/lib.rs
- src/lib.rs
- tests/systems_basic.rs
This PR allows users to request queries as parameters in basic `#[system]` macro invocations. This allows a system to request multiple queries without the user having to construct them themselves. It also adds these queries to the system (via `SystemBuilder`), which means (in most cases) users won't need to use `#[read_component(T)]`/`#[write_component(T)]` attributes, and the queries persist between each run of the system, allowing for some level of caching between runs.
For example, prior to this PR:
```rust
#[system]
#[read_component(A, B)]
#[write_component(C)]
fn my_system(world: &mut SubWorld) {
let query_a = <(&A, &mut C)>::query();
for (a, c) in query_a.iter_mut(world) {
...
}
let query_b = <(&B, &mut C)>::query();
for (b, c) in query_b.iter_mut(world) {
...
}
}
```
Can now be …
> Allow Queries to be requested as parameters in #[system]

- src/internals/entity.rs
Added `size_hint` which would improve performance of things like `Allocate::new().take(100).collect::<Vec<_>>()`.
Also removed unused lifetime, since it literally didn't do anything.
Just a little change I did while benchmarking `Allocate::next`.
The speed increase was tested in the benchmark; `Allocate::new().take(n).collect()` runs up to 75% faster, based on `n`.
> Add `size_hint` implementation to entity alloc iterator

- Cargo.toml
The uuid crate is only needed for the serialize feature. 
Setting the dependency to optional so it won't be compiled if one decide to disable the serialize feature.
> fix: Set uuid as an optional dependency dependent of serialize feature

- src/internals/subworld.rs
`SubWorld` currently implements `Clone`. This was a mistake and never should have been released, but has been like this since v0.3.0.
`SubWorld` allows access rights (read/write access to certain components and certain entities) to be split, to allow one query to access some entities without borrowing the entirety of the world.
There are unsafe blocks inside both `SubWorld` and queries which assume that any mutable accesses to the world that they are allowed to perform have already been validated, which is the responsibility of the `SubWorld` and enforced by the logic of `SubWorld::split`.
Allowing the `SubWorld` to be cloned entirely invalidates this assumption, as a `SubWorld` with mutable access to a given component can be cloned and both copies will then permit aliased mutable access …
> Removed #[derive(Clone)] from SubWorld

- src/internals/world.rs
Adds a new method for `World` struct.
The function extends a user-provided collection directly instead of writing to internal buffer and then giving a reference to the contents of the buffer.
Because [`Vec::extend_from_slice` simply redirects to `Vec::extend`](https://doc.rust-lang.org/src/alloc/vec/mod.rs.html#1907), `World::extend` was changed to use `World::extend_out`; there should be no performance difference.
Also `World::push` uses `World::extend_out` to avoid allocation in `World::extend`.
Mostly to allow users skip an intermediate buffer to do insertions a little bit faster.
Fixes #218.
Well, not so much of an issue fix, because the fix for the issue is really simple:
```rust
// instead of this:
let entities = world.extend(v);
// write this:
let entities = …
```
> New `World::extend_out` function

- Cargo.toml
- codegen/Cargo.toml
- codegen/src/lib.rs
- tests/failures/par_mut_command.stderr
- tests/failures/par_mut_resource.stderr
- tests/failures/par_mut_world.stderr
If a crate uses legion and wants to reexport it, it works for all
functionality except the codegen.
Using the :: prefix forces the dependency to exist as a crate for calling
project - which in turn forces the user of the third-party crate to keep
legion in their own Cargo.toml and make sure the versions match over
time.
If a crate uses legion and wants to reexport it, it works for all
functionality except the codegen.
Using the :: prefix forces the dependency to exist as a crate for calling
project - which in turn forces the user of the third-party crate to keep
legion in their own Cargo.toml and make sure the versions match over
time.
This has been tested by compiling the Amethyst `sampler_interpolation` system with the feature flag and without the extra dependency.
> Allow use of reexported legion crate for codegen

- Cargo.toml
- codegen/Cargo.toml
- codegen/src/lib.rs
The reexport feature doesn't work because the cfg! macro is expanded in the caller code.
This means that the feature is only enabled if the calling crate has a feature called "reexport", and not if that feature is enabled in the legion crate.
Using `#[cfg(...)]` makes the feature check happen at legion_codegen's compile-time, which fixes the above issue.
The biggest challenge with this change is to get around the tests. The automated tests run with `--all-features`, which enables the `reexport` feature for the tests which then fail. By adding two features which must not be enabled at the same time, we can get around this issue.
This fix is necessary for the feature to work as intended.
This has been tested in a local setup with amethyst using legion as a local dependency with this change.
> Fix bug wrong macro expansion order for reexport feature

- src/internals/entity.rs
- src/internals/subworld.rs
- src/internals/systems/command.rs
- src/internals/systems/system.rs
Whenever a user needs another copy of a system, they wouldn't need to call the system factory fn, reducing boilerplate code
Whenever a user needs another copy of a system, they wouldn't need to call the system factory fn, reducing boilerplate code
All I did was make sure that the compiler wasn't complaining and ran cargo test with no failure
> Deriving System with Clone and its recursive elements

- src/internals/systems/schedule.rs
Allow passing `Box<dyn ParallelRunnable>` and `Box<dyn Runnable>` directly.
I am storing my own systems in a `Vec<Box<dyn Runnable>>` for sorting before passing them into legion, but I cannot pass a `Box<dyn Runnable>` directly because of the explicit type requirements.
The code passes clippy lint. I don't think testing is necessary since this is pretty straightforward.
> Added add_system_boxed and add_thread_local_boxed
